import type { Metadata } from "next";
import { Inter, Yusei_Magic } from "next/font/google";
import "./globals.css";
import Sound from "@/components/Sound";

// const inter = Inter({ subsets: ["latin"] });
const yusei = Yusei_Magic({ preload: false, weight: "400" });

export const metadata: Metadata = {
  title: "Naufal Husnianto - Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={yusei.className}>
        {children}
        <Sound />
      </body>
    </html>
  );
}
